
import java.awt.Color;

public class Blackjack extends javax.swing.JFrame {

    // ===== GAME STATE =====
    private int playerTotal = 0;
    private int dealerTotal = 0;

    private java.util.Random rand = new java.util.Random();

    private boolean gameOver = false;

    private int drawCard() {
        int card = rand.nextInt(10) + 1; // values 1–10
        return card;
    }

    /**
     * Creates new form Blackjack
     */
    public Blackjack() {
        initComponents();

        // --- Colors ---
        Color BG = new Color(0x0B0B0F);
        Color PANEL = new Color(0x0F1733);
        Color GOLD = new Color(0xFFD700);
        Color NEON_GREEN = new Color(0x00FF99);
        Color NEON_RED = new Color(0xFF4444);
        Color CARD_BG = new Color(0x111827);
        Color GLOW = new Color(0x2E3BFF);

// --- Frame general ---
        getContentPane().setBackground(BG);
        setLocationRelativeTo(null); // center on screen

// --- Labels (totals, titles) ---
        labelDealerTotal.setForeground(GOLD);
        labelDealerTotal.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        labelPlayerTotal.setForeground(NEON_GREEN);
        labelPlayerTotal.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

// --- Buttons styles ---
        buttonHit.setBackground(NEON_GREEN);
        buttonHit.setForeground(new Color(0x0B0B0F));
        buttonHit.setFocusPainted(false);
        buttonHit.setBorder(new javax.swing.border.LineBorder(GOLD, 2, true));
        buttonStand.setBackground(NEON_RED);
        buttonStand.setForeground(new Color(0x0B0B0F));
        buttonStand.setFocusPainted(false);
        buttonStand.setBorder(new javax.swing.border.LineBorder(GOLD, 2, true));
        buttonRestart.setBackground(GOLD);
        buttonRestart.setForeground(new Color(0x0B0B0F));
        buttonRestart.setFocusPainted(false);
        buttonRestart.setBorder(new javax.swing.border.LineBorder(GLOW, 2, true));

        startGame();
    }

    private void startGame() {
        playerTotal = drawCard() + drawCard();
        dealerTotal = drawCard() + drawCard();
        gameOver = false;
        updateLabels();
    }

    private void updateLabels() {
        labelPlayerTotal.setText("Player Total: " + playerTotal);

        if (gameOver) {
            labelDealerTotal.setText("Dealer Total: " + dealerTotal);
        } else {
            labelDealerTotal.setText("Dealer Total: ?");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDealerTotal = new javax.swing.JLabel();
        labelPlayerTotal = new javax.swing.JLabel();
        buttonHit = new javax.swing.JButton();
        buttonStand = new javax.swing.JButton();
        buttonRestart = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuExit1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        labelDealerTotal.setBackground(new java.awt.Color(0, 102, 51));
        labelDealerTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        labelDealerTotal.setForeground(new java.awt.Color(255, 255, 255));
        labelDealerTotal.setText("Dealer Total:");

        labelPlayerTotal.setBackground(new java.awt.Color(102, 0, 102));
        labelPlayerTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        labelPlayerTotal.setForeground(new java.awt.Color(255, 255, 255));
        labelPlayerTotal.setText("Player Total:");

        buttonHit.setBackground(new java.awt.Color(153, 153, 0));
        buttonHit.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        buttonHit.setForeground(new java.awt.Color(0, 0, 0));
        buttonHit.setText("HIT");
        buttonHit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHitActionPerformed(evt);
            }
        });

        buttonStand.setBackground(new java.awt.Color(255, 51, 255));
        buttonStand.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        buttonStand.setForeground(new java.awt.Color(0, 0, 0));
        buttonStand.setText("STAND");
        buttonStand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStandActionPerformed(evt);
            }
        });

        buttonRestart.setBackground(new java.awt.Color(0, 255, 102));
        buttonRestart.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        buttonRestart.setForeground(new java.awt.Color(0, 0, 0));
        buttonRestart.setText("RESTART");
        buttonRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRestartActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuExit1.setText("EXIT GAME");
        jMenuExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExit1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(buttonRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(buttonStand, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(buttonHit)))
                .addGap(310, 310, 310)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPlayerTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDealerTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(labelDealerTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(buttonHit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStand, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 109, Short.MAX_VALUE)
                        .addComponent(labelPlayerTotal)
                        .addGap(142, 142, 142))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHitActionPerformed
        if (gameOver) {
            return;
        }

        int card = drawCard();
        playerTotal += card;

        if (playerTotal >= 21) { // handle 21 as well
            gameOver = true;
            if (playerTotal > 21) {
                labelPlayerTotal.setText("Player Total: " + playerTotal + " (BUST!)");
            } else {
                labelPlayerTotal.setText("Player Total: " + playerTotal + " (WIN!)");
            }
            // Optionally reveal dealer total
            labelDealerTotal.setText("Dealer Total: " + dealerTotal);
        } else {
            updateLabels();
        }

    }//GEN-LAST:event_buttonHitActionPerformed

    private void buttonStandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStandActionPerformed
        if (gameOver) {
            return;
        }

        // Dealer hits until 17+
        while (dealerTotal < 17) {
            dealerTotal += drawCard();
        }

        gameOver = true;

        // Decide winner
        if (dealerTotal > 21 || playerTotal > dealerTotal) {
            labelPlayerTotal.setText("Player Total: " + playerTotal + " (WIN!)");
        } else if (dealerTotal == playerTotal) {
            labelPlayerTotal.setText("Player Total: " + playerTotal + " (DRAW)");
        } else {
            labelPlayerTotal.setText("Player Total: " + playerTotal + " (LOSE)");
        }

        labelDealerTotal.setText("Dealer Total: " + dealerTotal);


    }//GEN-LAST:event_buttonStandActionPerformed

    private void buttonRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRestartActionPerformed
        startGame();
    }//GEN-LAST:event_buttonRestartActionPerformed

    private void jMenuExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExit1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuExit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Blackjack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Blackjack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Blackjack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Blackjack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Blackjack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHit;
    private javax.swing.JButton buttonRestart;
    private javax.swing.JButton buttonStand;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit1;
    private javax.swing.JLabel labelDealerTotal;
    private javax.swing.JLabel labelPlayerTotal;
    // End of variables declaration//GEN-END:variables
}
