
import java.awt.Color;
import java.awt.Font;

public class Casinohub extends javax.swing.JFrame {

    /**
     * Creates new form CasinoHub
     */
    // NEON / casino theme colors
    private final Color BG = new Color(0x0B0B0F);          // dark background
    private final Color BUTTON_NEON_GREEN = new Color(0x00FF99);
    private final Color BUTTON_NEON_RED = new Color(0xFF4444);
    private final Color BUTTON_GOLD = new Color(0xFFD700);
    private final Color TITLE_GLOW = new Color(0x2E3BFF);
    private final Font TITLE_FONT = new Font("Gabriola", Font.BOLD, 28);
    private final Font SUBTITLE_FONT = new Font("Lucida Console", Font.BOLD, 24);
    private final Font BUTTON_FONT = new Font("Comic Sans MS", Font.BOLD, 18);

    public Casinohub() {
        initComponents();

        getContentPane().setBackground(BG); // dark casino vibe

// Title
        jLabel1.setForeground(TITLE_GLOW);
        jLabel1.setFont(TITLE_FONT);

// Subtitle
        jLabel2.setForeground(BUTTON_GOLD);
        jLabel2.setFont(SUBTITLE_FONT);

// Buttons
        jButtonPlayBlackJack.setBackground(BUTTON_NEON_GREEN);
        jButtonPlayBlackJack.setForeground(BG); // text color
        jButtonPlayBlackJack.setFont(BUTTON_FONT);
        jButtonPlayBlackJack.setFocusPainted(false);
        jButtonPlayBlackJack.setBorder(new javax.swing.border.LineBorder(BUTTON_GOLD, 2, true));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonPlayBlackJack = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO THE CASINO HUB");

        jLabel2.setFont(new java.awt.Font("Lucida Console", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SELECT A GAME:");

        jButtonPlayBlackJack.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonPlayBlackJack.setText("BlackJack");
        jButtonPlayBlackJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayBlackJackActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuExit.setText("Exit Hub");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButtonPlayBlackJack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel2)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(jButtonPlayBlackJack)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlayBlackJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayBlackJackActionPerformed

        new Blackjack().setVisible(true);
        this.dispose(); // close hub

        jButtonPlayBlackJack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPlayBlackJack.setBackground(TITLE_GLOW); // glow effect
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPlayBlackJack.setBackground(BUTTON_NEON_GREEN); // revert color
            }
        });
    }//GEN-LAST:event_jButtonPlayBlackJackActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Casinohub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Casinohub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Casinohub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Casinohub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Casinohub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPlayBlackJack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    // End of variables declaration//GEN-END:variables
}
